data_log_name: bigcodebench

# BigCodeBench dataset configuration
dataset_id_or_path: bigcode/bigcodebench
dataset_local_directory: ${dataset_id_or_path}
dataset_configuration: null

# Worker models for orchestration
worker_models:
  - Qwen/Qwen2.5-3B-Instruct
  - microsoft/Phi-3-mini-4k-instruct
  - meta-llama/Llama-3.2-3B-Instruct
  - Qwen/Qwen2.5-Coder-3B-Instruct

max_routing_steps: 5

# Few-shot examples
num_few_shot_examples: 3

make_dataset_fn:
  _target_: orchestrator.data_utils.orchestrator_dataset.OrchestratorDataset
  worker_models: ${worker_models}
  max_routing_steps: ${max_routing_steps}
  split: train
  max_samples: null
  seed: 42
  apply_chat_template: true
  max_prompt_length: 2048
  tokenizer_kwargs: {}
  num_few_shot_examples: ${num_few_shot_examples}

make_eval_dataset_fn:
  _target_: orchestrator.data_utils.orchestrator_dataset.OrchestratorDataset
  worker_models: ${worker_models}
  max_routing_steps: ${max_routing_steps}
  split: test
  max_samples: 100
  seed: 42
  apply_chat_template: true
  max_prompt_length: 2048
  tokenizer_kwargs: {}
  num_few_shot_examples: ${num_few_shot_examples}

