defaults:
  - base
  - _self_ 

# https://huggingface.co/datasets/HuggingFaceTB/smoltalk
data_log_name: smoltalk

dataset_id_or_path: HuggingFaceTB/smoltalk


completion_only_training: True
custom_start_of_response: ~
dataset_configuration: all

make_dataset_fn:
  _target_: custom_data.sft_data.load_formatted_sft_dataset
  process_line_fn:
    _target_: custom_data.sft_data.get_process_line_fn
    dataset_id_or_path: ${dataset_id_or_path}
  completion_only_training: ${completion_only_training}
  custom_start_of_response: ${custom_start_of_response}




