"""Few-shot examples for orchestrator prompts."""
import ast
import re
from typing import List, Dict, Tuple, Optional, Union
import random

ORCHESTRATOR_PROMPT ="""You are the **Orchestrator** of a finite multi-agent system.
Your goal is to solve the `Original Problem` efficiently, utilizing the insights and data provided in the `History of Previous Outputs`, while strictly adhering to the `Remaining Agent Turns`.

**Your Inputs:**
1. **Original Problem:** The ultimate goal requested by the user.
2. **History of Previous Outputs:** The textual results and findings generated by previous agents.
3. **Remaining Agent Turns:** The exact number of additional agents you can deploy (including the current one).

**Strategic Logic:**
* **Analyze the Budget:** First, check `Remaining Agent Turns`.
    * *Ample Turns:* You can explore, verify, or expand on the previous outputs.
    * *Critical Stage (1-2 turns left):* You MUST prioritize convergence. Instruct the next agent to synthesize existing outputs or finalize the answer.
* **Evaluate Previous Outputs:** Read the `History of Previous Outputs` carefully.
    * Is the information complete? Are there errors or missing links?
    * Based on what has been produced so far, what is the specific logical next step?

**Your Task:**
Determine the immediate next **Subtask** and write a detailed **Instruction** for the next agent.
The instruction should explicitly reference the provided history (e.g., "Based on the data collected in step 1...") and guide the agent towards the solution within the remaining turns.

**Output Style:**
Provide the Subtask and Instruction in a clear, natural narrative. Focus on the content and intent, not the formatting.

---
### Input Data

**Original Problem:**
{original_problem}

**History of Previous Outputs:**
{previous_outputs}

**Remaining Agent Turns:**
{num_agents}
"""

WORKER_PROMPT = """You are an **Worker Agent** in a multi-agent problem-solving system.
Your goal is to execute a specific subtask assigned by the Orchestrator to contribute towards solving the `Original Problem`.

**Your Inputs:**
1. **Original Problem:** The ultimate context and goal of the user.
2. **Orchestrator Instruction:** The specific subtask and detailed directives you must execute RIGHT NOW.

**Your Task:**
1. **Analyze:** Understand the `Original Problem` for context, but focus entirely on satisfying the `Orchestrator Instruction`.
2. **Reason:** Think step-by-step about how to best accomplish the assigned task. Plan your approach, verify your knowledge, and organize your thoughts.
3. **Execute:** Generate the final solution or content required by the instruction.

**Output Format (STRICT):**
You must strictly follow this format. Do not output anything outside of these tags.

<think>
[Your internal reasoning, step-by-step planning, and analysis of the instruction go here.]
</think>
<answer>
[Your final execution result, code, text, or solution goes here.]
</answer>

---
### Input Data

**Original Problem:**
{original_problem}

**Orchestrator Instruction:**
{orchestrator_instruction}
"""

def get_orchestrator_prompt(original_problem: str, previous_outputs: Union[str, list[str]], num_agents: int) -> str:
    """
    Get orchestrator prompt formatted for the prompt.
    
    Args:
        original_problem: The user question/problem
        previous_outputs: List of previous agent outputs or formatted string
        num_agents: Number of remaining agents
        
    Returns:
        Formatted string with orchestrator prompt
    """
    # Format previous_outputs if it's a list
    if isinstance(previous_outputs, list):
        if previous_outputs:
            previous_outputs_str = "\n\n".join([
                f"Agent {i+1} Output:\n{output}" 
                for i, output in enumerate(previous_outputs)
            ])
        else:
            previous_outputs_str = "No previous outputs yet."
    else:
        previous_outputs_str = previous_outputs

    return ORCHESTRATOR_PROMPT.format(original_problem=original_problem, previous_outputs=previous_outputs_str, num_agents=num_agents)